### ISSUE TITLE
[Question] Is it possible to have randomized sets of outfits for individual girls?

### ISSUE THREAD

**Issue by narkafh** [jalil49/Cosplay-Academy#1]
I haven't installed your mod yet, but looking through it, it looks like you can create a set of outfits that *all* the girls can pick from. Is it possible to have one girl to have her own selection of swimsuits while a different girl has her own separate selection of swimsuits (not just swimsuits but any uniform type)? How difficult would it be to implement this? This has been something I've been wanting for a while and what you have seems pretty close. I haven't tried your Additional Card Info mod yet either, but maybe it would be possible to use that to specify a directory for a girl's possible outfits?

**Comment by jalil49** [comment]
If the purpose of having separate directory is to handle hair accessories so they don't end up bald, hair accessories are kept by default and using ACI will give better control over what is kept.

**Comment by jalil49** [comment]
I'll have to rewrite how my decider works, but I suppose it is possible to do so.
If I want to characters to use Hstates it would use the same folder structure and hopefully just pull generally if specific is empty.

**Comment by narkafh** [comment]
Maybe I misinterpreted what ACI did, but I was thinking you might have to add a field per uniform type that was something along the lines of:
- in school: [some directory with coordinates]
- going home: [some other directory with coordinates]
- gym uniform: [some other directory with coordinates]
- ...

I'll install both mods tonight so I can get a better understanding of them.

It'd be awesome if you're able to achieve what I'm imagining, but I hope I'm not imposing too much work on you.

**Comment by jalil49** [comment]
Think I got the idea, gonna implement the required folder name in the next version of ACI and work on the functionality after the next version of Cosplay Academy.

**Comment by narkafh** [comment]
Awesome, can't wait.

**Comment by LangyMD** [comment]
I'm just going to post here my agreement with this request. It'd allow you to have personalized clothes for each character, but randomizing between them and - more important for me - switching between clothing options based off of the character's H experience.

Thanks for working on this!
